name: divea
channels:
  - defaults
  - pytorch
  - conda-forge
  - dglteam
dependencies:
  - python=3.6
  - tensorflow-gpu==1.15
  - pytorch==1.4.0
  - torchvision==0.5.0
  - torchaudio
  - dgl-cuda10.0==0.5.3
  - pip
  - pip:
      - pandas==1.1.5
      - tqdm==4.56.0
      - keras==2.2.4
      - nvidia-ml-py3==7.352.0
      - requests==2.25.1
      - scikit-learn==0.23.2


